dependencies:
- alias: zeebe
  name: zeebe-cluster
  repository: https://helm.zeebe.io
  version: 0.0.122
- alias: operate
  name: zeebe-operate
  repository: https://helm.zeebe.io
  version: 0.0.24
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.2
